// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"

	"github.com/volatiletech/sqlboiler/v4/boil"
)

type Entity interface {
	Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error)

	Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error)

	Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error

	Reload(ctx context.Context, exec boil.ContextExecutor) error

	Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error)

	Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns boil.Columns, insertColumns boil.Columns) error
}
