// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"

	"github.com/volatiletech/sqlboiler/v4/boil"
)

type Query[T Entity] interface {
	All(ctx context.Context, exec boil.ContextExecutor) ([]T, error)

	Count(ctx context.Context, exec boil.ContextExecutor) (int64, error)

	DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error)

	Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error)

	One(ctx context.Context, exec boil.ContextExecutor) (T, error)

	UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error)

}
